---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:

  - name: Check if Podman package is installed
    ansible.builtin.assert:
      that:
        - "'podman' in ansible_facts.packages"
      fail_msg: "Podman is not installed."